 spring:
   cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/12app/petclinic.git
          username: "mhari.tech"    
          password: "09g81a0505"
          

 eureka:
  client:
   serviceUrl:
     defaultZone: http://discovery-service:8761/eureka
