#zuul:
#  prefix: /api
#  ignoredServices: '*'
#  routes:
#    vets-service: /vet/**
#    visits-service: /visit/**
#    customer-service: /customer/**
#    api-gateway: /gateway/**

   
swagger: 
  config: 
    refreshrate: 5000
    
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 6000
  eureka:
    enabled: true 
    
    
eureka:
  client:
    instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    server:
      wait-time-in-ms-when-sync-empty: 0